SPELLS = [
  {'name': "Abi-Dalzim's Horrid Wilting", 'level': 8, 'school': 'NEC'},
  {'name': "Absorb Elements", 'level': 1, 'school': 'ABJ'},
  {'name': "Acid Splash", 'level': 0, 'school': 'EVO'},
  {'name': "Aganazzar's Scorcher", 'level': 2, 'school': 'EVO'},
  {'name': "Aid", 'level': 2, 'school': 'ABJ'},
  {'name': "Alarm", 'level': 1, 'school': 'ABJ'},
  {'name': "Alter Self", 'level': 2, 'school': 'TRA'},
  {'name': "Animal Friendship", 'level': 1, 'school': 'ENC'},
  {'name': "Animal Messenger", 'level': 2, 'school': 'ENC'},
  {'name': "Animal Shapes", 'level': 8, 'school': 'TRA'},
  {'name': "Animate Dead", 'level': 3, 'school': 'NEC'},
  {'name': "Animate Objects", 'level': 5, 'school': 'TRA'},
  {'name': "Antagonize", 'level': 3, 'school': 'ENC'},
  {'name': "Antilife Shell", 'level': 5, 'school': 'ABJ'},
  {'name': "Antimagic", 'level': 8, 'school': 'ABJ'},
  {'name': "Antipathy/Sympathy", 'level': 8, 'school': 'ENC'},
  {'name': "Arcane Eye", 'level': 4, 'school': 'DIV'},
  {'name': "Arcane Gate", 'level': 6, 'school': 'CON'},
  {'name': "Arcane Lock", 'level': 2, 'school': 'ABJ'},
  {'name': "Arcane Vigor", 'level': 2, 'school': 'ABJ'},
  {'name': "Armor of Agathys", 'level': 1, 'school': 'ABJ'},
  {'name': "Arms of Hadar", 'level': 1, 'school': 'CON'},
  {'name': "Ashardalon's Stride", 'level': 3, 'school': 'TRA'},
  {'name': "Astral Projection", 'level': 9, 'school': 'NEC'},
  {'name': "Augury", 'level': 2, 'school': 'DIV'},
  {'name': "Aura of Life", 'level': 4, 'school': 'ABJ'},
  {'name': "Aura of Purity", 'level': 4, 'school': 'ABJ'},
  {'name': "Aura of Vitality", 'level': 3, 'school': 'EVO'},
  {'name': "Awaken", 'level': 5, 'school': 'TRA'},
  {'name': "Bane", 'level': 1, 'school': 'ENC'},
  {'name': "Banishing Smite", 'level': 5, 'school': 'CON'},
  {'name': "Banishment", 'level': 4, 'school': 'ABJ'},
  {'name': "Barkskin", 'level': 2, 'school': 'TRA'},
  {'name': "Beacon of Hope", 'level': 3, 'school': 'ABJ'},
  {'name': "Beast Bond", 'level': 1, 'school': 'DIV'},
  {'name': "Beast Sense", 'level': 2, 'school': 'DIV'},
  {'name': "Befuddlement", 'level': 8, 'school': 'ENC'},
  {'name': "Bestow Curse", 'level': 3, 'school': 'NEC'},
  {'name': "Bigby's Hand", 'level': 5, 'school': 'EVO'},
  {'name': "Blade Barrier", 'level': 6, 'school': 'EVO'},
  {'name': "Blade of Disaster", 'level': 9, 'school': 'CON'},
  {'name': "Blade Ward", 'level': 0, 'school': 'ABJ'},
  {'name': "Bless", 'level': 1, 'school': 'ENC'},
  {'name': "Blight", 'level': 4, 'school': 'NEC'},
  {'name': "Blinding Smite", 'level': 3, 'school': 'EVO'},
  {'name': "Blindness/Deafness", 'level': 2, 'school': 'NEC'},
  {'name': "Blink", 'level': 3, 'school': 'TRA'},
  {'name': "Blur", 'level': 2, 'school': 'ILL'},
  {'name': "Bolt Strike", 'level': 5, 'school': 'EVO'},
  {'name': "Bones of the Earth", 'level': 6, 'school': 'TRA'},
  {'name': "Booming Blade", 'level': 0, 'school': 'EVO'},
  {'name': "Borrowed Knowledge", 'level': 2, 'school': 'DIV'},
  {'name': "Burning Hands", 'level': 1, 'school': 'EVO'},
  {'name': "Call Lightning", 'level': 3, 'school': 'CON'},
  {'name': "Calm Emotions", 'level': 2, 'school': 'ENC'},
  {'name': "Catapult", 'level': 1, 'school': 'TRA'},
  {'name': "Catnap", 'level': 3, 'school': 'ENC'},
  {'name': "Cause Fear", 'level': 1, 'school': 'NEC'},
  {'name': "Ceremony", 'level': 1, 'school': 'ABJ'},
  {'name': "Chain Lightning", 'level': 6, 'school': 'EVO'},
  {'name': "Chaos Bolt", 'level': 1, 'school': 'EVO'},
  {'name': "Charm Monster", 'level': 4, 'school': 'ENC'},
  {'name': "Charm Person", 'level': 1, 'school': 'ENC'},
  {'name': "Chill Touch", 'level': 0, 'school': 'NEC'},
  {'name': "Chromatic Orb", 'level': 1, 'school': 'EVO'},
  {'name': "Circle of Death", 'level': 6, 'school': 'NEC'},
  {'name': "Circle of Power", 'level': 5, 'school': 'ABJ'},
  {'name': "Clairvoyance", 'level': 3, 'school': 'DIV'},
  {'name': "Clone", 'level': 8, 'school': 'NEC'},
  {'name': "Cloud of Daggers", 'level': 2, 'school': 'CON'},
  {'name': "Cloudkill", 'level': 5, 'school': 'CON'},
  {'name': "Color Spray", 'level': 1, 'school': 'ILL'},
  {'name': "Command", 'level': 1, 'school': 'ENC'},
  {'name': "Commune", 'level': 5, 'school': 'DIV'},
  {'name': "Commune with Nature", 'level': 5, 'school': 'DIV'},
  {'name': "Compelled Duel", 'level': 1, 'school': 'ENC'},
  {'name': "Comprehend Languages", 'level': 1, 'school': 'DIV'},
  {'name': "Compulsion", 'level': 4, 'school': 'ENC'},
  {'name': "Cone of Cold", 'level': 5, 'school': 'EVO'},
  {'name': "Confusion", 'level': 4, 'school': 'ENC'},
  {'name': "Conjure Animals", 'level': 3, 'school': 'CON'},
  {'name': "Conjure Barrage", 'level': 3, 'school': 'CON'},
  {'name': "Conjure Celestial", 'level': 7, 'school': 'CON'},
  {'name': "Conjure Elemental", 'level': 5, 'school': 'CON'},
  {'name': "Conjure Fey", 'level': 6, 'school': 'CON'},
  {'name': "Conjure Minor Elemental", 'level': 4, 'school': 'CON'},
  {'name': "Conjure Volley", 'level': 5, 'school': 'CON'},
  {'name': "Conjure Woodland Beings", 'level': 4, 'school': 'CON'},
  {'name': "Contact Other Plane", 'level': 5, 'school': 'DIV'},
  {'name': "Contagion", 'level': 5, 'school': 'NEC'},
  {'name': "Contingency", 'level': 6, 'school': 'EVO'},
  {'name': "Continual Flame", 'level': 2, 'school': 'EVO'},
  {'name': "Control Flames", 'level': 0, 'school': 'TRA'},
  {'name': "Control Water", 'level': 4, 'school': 'TRA'},
  {'name': "Control Weather", 'level': 8, 'school': 'TRA'},
  {'name': "Control Winds", 'level': 5, 'school': 'TRA'},
  {'name': "Cordon of Arrows", 'level': 2, 'school': 'TRA'},
  {'name': "Counterspell", 'level': 3, 'school': 'ABJ'},
  {'name': "Create Bonfire", 'level': 0, 'school': 'CON'},
  {'name': "Create Food and Water", 'level': 3, 'school': 'CON'},
  {'name': "Create Homunculus", 'level': 6, 'school': 'TRA'},
  {'name': "Create or Destroy Water", 'level': 1, 'school': 'TRA'},
  {'name': "Create Undead", 'level': 6, 'school': 'NEC'},
  {'name': "Creation", 'level': 5, 'school': 'ILL'},
  {'name': "Crown of Madness", 'level': 2, 'school': 'ENC'},
  {'name': "Crown of Stars", 'level': 7, 'school': 'EVO'},
  {'name': "Crusader's Mantle", 'level': 3, 'school': 'EVO'},
  {'name': "Cure Wounds", 'level': 1, 'school': 'ABJ'},
  {'name': "Dancing Lights", 'level': 0, 'school': 'ILL'},
  {'name': "Danse Macabre", 'level': 5, 'school': 'NEC'},
  {'name': "Dark Star", 'level': 8, 'school': 'EVO'},
  {'name': "Darkness", 'level': 2, 'school': 'EVO'},
  {'name': "Darkvision", 'level': 2, 'school': 'TRA'},
  {'name': "Dawn", 'level': 5, 'school': 'EVO'},
  {'name': "Daylight", 'level': 3, 'school': 'EVO'},
  {'name': "Death Ward", 'level': 4, 'school': 'ABJ'},
  {'name': "Delayed Blast Fireball", 'level': 7, 'school': 'EVO'},
  {'name': "Demiplane", 'level': 8, 'school': 'CON'},
  {'name': "Destructive Wave", 'level': 5, 'school': 'EVO'},
  {'name': "Detect Evil and Good", 'level': 1, 'school': 'DIV'},
  {'name': "Detect Magic", 'level': 1, 'school': 'DIV'},
  {'name': "Detect Poison and Disease", 'level': 1, 'school': 'DIV'},
  {'name': "Detect Thoughts", 'level': 2, 'school': 'DIV'},
  {'name': "Dimension Door", 'level': 4, 'school': 'CON'},
  {'name': "Disguise Self", 'level': 1, 'school': 'ILL'},
  {'name': "Disintegrate", 'level': 6, 'school': 'TRA'},
  {'name': "Dispel Evil and Good", 'level': 5, 'school': 'ABJ'},
  {'name': "Dispel Magic", 'level': 3, 'school': 'ABJ'},
  {'name': "Dissonant Whispers", 'level': 1, 'school': 'ENC'},
  {'name': "Divination", 'level': 4, 'school': 'DIV'},
  {'name': "Divine Favor", 'level': 1, 'school': 'EVO'},
  {'name': "Divine Lightning", 'level': 3, 'school': 'EVO'},
  {'name': "Divine Smite", 'level': 1, 'school': 'TRA'},
  {'name': "Divine Word", 'level': 7, 'school': 'EVO'},
  {'name': "Dominate Beast", 'level': 4, 'school': 'ENC'},
  {'name': "Dominate Monster", 'level': 8, 'school': 'ENC'},
  {'name': "Dominate Person", 'level': 5, 'school': 'ENC'},
  {'name': "Draconic Transformation", 'level': 7, 'school': 'TRA'},
  {'name': "Dragon's Breath", 'level': 2, 'school': 'TRA'},
  {'name': "Drawmij's Instant Summons", 'level': 6, 'school': 'CON'},
  {'name': "Dream", 'level': 5, 'school': 'ILL'},
  {'name': "Druid Grove", 'level': 6, 'school': 'ABJ'},
  {'name': "Druidcraft", 'level': 0, 'school': 'TRA'},
  {'name': "Dust Devil", 'level': 2, 'school': 'CON'},
  {'name': "Earth Tremor", 'level': 1, 'school': 'EVO'},
  {'name': "Earthbind", 'level': 2, 'school': 'TRA'},
  {'name': "Earthquake", 'level': 8, 'school': 'TRA'},
  {'name': "Eldritch Blast", 'level': 0, 'school': 'EVO'},
  {'name': "Elemental Bane", 'level': 4, 'school': 'TRA'},
  {'name': "Elemental Weapon", 'level': 3, 'school': 'TRA'},
  {'name': "Elementalism", 'level': 0, 'school': 'TRA'},
  {'name': "Enemies Abound", 'level': 3, 'school': 'ENC'},
  {'name': "Enervation", 'level': 5, 'school': 'NEC'},
  {'name': "Enhance Ability", 'level': 2, 'school': 'TRA'},
  {'name': "Enlarge/Reduce", 'level': 2, 'school': 'TRA'},
  {'name': "Ensnaring Strike", 'level': 1, 'school': 'CON'},
  {'name': "Entangle", 'level': 1, 'school': 'CON'},
  {'name': "Enthrall", 'level': 2, 'school': 'ENC'},
  {'name': "Erupting Earth", 'level': 3, 'school': 'TRA'},
  {'name': "Etherealness", 'level': 7, 'school': 'TRA'},
  {'name': "Evard's Black Tentacles", 'level': 4, 'school': 'CON'},
  {'name': "Expeditious Retreat", 'level': 1, 'school': 'TRA'},
  {'name': "Eyebite", 'level': 6, 'school': 'NEC'},
  {'name': "Fabricate", 'level': 4, 'school': 'TRA'},
  {'name': "Faerie Fire", 'level': 1, 'school': 'EVO'},
  {'name': "False Life", 'level': 1, 'school': 'NEC'},
  {'name': "Far Step", 'level': 5, 'school': 'CON'},
  {'name': "Fear", 'level': 3, 'school': 'ILL'},
  {'name': "Feather Fall", 'level': 1, 'school': 'TRA'},
  {'name': "Feign Death", 'level': 3, 'school': 'NEC'},
  {'name': "Find Familiar", 'level': 1, 'school': 'CON'},
  {'name': "Find Greater Steed", 'level': 4, 'school': 'CON'},
  {'name': "Find Steed", 'level': 2, 'school': 'CON'},
  {'name': "Find the Path", 'level': 6, 'school': 'DIV'},
  {'name': "Find Traps", 'level': 2, 'school': 'DIV'},
  {'name': "Finger of Death", 'level': 7, 'school': 'NEC'},
  {'name': "Fire Bolt", 'level': 0, 'school': 'EVO'},
  {'name': "Fire Shield", 'level': 4, 'school': 'EVO'},
  {'name': "Fire Storm", 'level': 7, 'school': 'EVO'},
  {'name': "Fireball", 'level': 3, 'school': 'EVO'},
  {'name': "Fizban's Platinum Shield", 'level': 6, 'school': 'ABJ'},
  {'name': "Flame Arrows", 'level': 3, 'school': 'TRA'},
  {'name': "Flame Blade", 'level': 2, 'school': 'EVO'},
  {'name': "Flame Strike", 'level': 5, 'school': 'EVO'},
  {'name': "Flaming Sphere", 'level': 2, 'school': 'CON'},
  {'name': "Flesh to Stone", 'level': 6, 'school': 'TRA'},
  {'name': "Fly", 'level': 3, 'school': 'TRA'},
  {'name': "Fog Cloud", 'level': 1, 'school': 'CON'},
  {'name': "Forbiddance", 'level': 6, 'school': 'ABJ'},
  {'name': "Forcecage", 'level': 7, 'school': 'EVO'},
  {'name': "Foresight", 'level': 9, 'school': 'DIV'},
  {'name': "Fortune's Favor", 'level': 2, 'school': 'DIV'},
  {'name': "Fount of Moonlight", 'level': 4, 'school': 'EVO'},
  {'name': "Freedom of Movement", 'level': 4, 'school': 'ABJ'},
  {'name': "Freedom of the Waves", 'level': 3, 'school': 'CON'},
  {'name': "Freedom of the Winds", 'level': 5, 'school': 'ABJ'},
  {'name': "Friends", 'level': 0, 'school': 'ENC'},
  {'name': "Frostbite", 'level': 0, 'school': 'EVO'},
  {'name': "Gaseous Form", 'level': 3, 'school': 'TRA'},
  {'name': "Gate", 'level': 9, 'school': 'CON'},
  {'name': "Geas", 'level': 5, 'school': 'ENC'},
  {'name': "Gentle Repose", 'level': 2, 'school': 'NEC'},
  {'name': "Giant Insect", 'level': 4, 'school': 'CON'},
  {'name': "Gift of Alacrity", 'level': 1, 'school': 'DIV'},
  {'name': "Glibness", 'level': 8, 'school': 'TRA'},
  {'name': "Globe of Invulnerability", 'level': 6, 'school': 'ABJ'},
  {'name': "Glyph of Warding", 'level': 3, 'school': 'ABJ'},
  {'name': "Goodberry", 'level': 1, 'school': 'TRA'},
  {'name': "Grasping Vine", 'level': 4, 'school': 'CON'},
  {'name': "Gravity Fissure", 'level': 6, 'school': 'EVO'},
  {'name': "Gravity Sinkhole", 'level': 4, 'school': 'EVO'},
  {'name': "Grease", 'level': 1, 'school': 'CON'},
  {'name': "Greater Invisibility", 'level': 4, 'school': 'ILL'},
  {'name': "Greater Restoration", 'level': 5, 'school': 'ABJ'},
  {'name': "Green-Flame Blade", 'level': 0, 'school': 'EVO'},
  {'name': "Guardian of Faith", 'level': 4, 'school': 'CON'},
  {'name': "Guardian of Nature", 'level': 4, 'school': 'TRA'},
  {'name': "Guards and Wards", 'level': 6, 'school': 'ABJ'},
  {'name': "Guidance", 'level': 0, 'school': 'DIV'},
  {'name': "Guiding Bolt", 'level': 1, 'school': 'EVO'},
  {'name': "Gust", 'level': 0, 'school': 'TRA'},
  {'name': "Gust of Wind", 'level': 2, 'school': 'EVO'},
  {'name': "Hail of Thorns", 'level': 1, 'school': 'CON'},
  {'name': "Hallow", 'level': 5, 'school': 'ABJ'},
  {'name': "Hallucinatory Terrain", 'level': 4, 'school': 'ILL'},
  {'name': "Harm", 'level': 6, 'school': 'NEC'},
  {'name': "Haste", 'level': 3, 'school': 'TRA'},
  {'name': "Heal", 'level': 6, 'school': 'ABJ'},
  {'name': "Healing Spirit", 'level': 2, 'school': 'CON'},
  {'name': "Healing Word", 'level': 1, 'school': 'ABJ'},
  {'name': "Heat Metal", 'level': 2, 'school': 'TRA'},
  {'name': "Hellish Rebuke", 'level': 1, 'school': 'EVO'},
  {'name': "Heroes's Feast", 'level': 6, 'school': 'CON'},
  {'name': "Heroism", 'level': 1, 'school': 'ENC'},
  {'name': "Hex", 'level': 1, 'school': 'ENC'},
  {'name': "Hold Monster", 'level': 5, 'school': 'ENC'},
  {'name': "Hold Person", 'level': 2, 'school': 'ENC'},
  {'name': "Holy Aura", 'level': 8, 'school': 'ABJ'},
  {'name': "Holy Weapon", 'level': 5, 'school': 'EVO'},
  {'name': "Hunger of Hadar", 'level': 3, 'school': 'CON'},
  {'name': "Hunter's Mark", 'level': 1, 'school': 'DIV'},
  {'name': "Hypnotic Pattern", 'level': 3, 'school': 'ILL'},
  {'name': "Ice Knife", 'level': 1, 'school': 'CON'},
  {'name': "Ice Storm", 'level': 4, 'school': 'EVO'},
  {'name': "Identify", 'level': 1, 'school': 'DIV'},
  {'name': "Illusory Dragon", 'level': 8, 'school': 'ILL'},
  {'name': "Illusory Script", 'level': 1, 'school': 'ILL'},
  {'name': "Immolation", 'level': 5, 'school': 'EVO'},
  {'name': "Immovable Object", 'level': 2, 'school': 'TRA'},
  {'name': "Imprisonment", 'level': 9, 'school': 'ABJ'},
  {'name': "Incendiary Cloud", 'level': 8, 'school': 'CON'},
  {'name': "Infernal Calling", 'level': 5, 'school': 'CON'},
  {'name': "Infestation", 'level': 0, 'school': 'CON'},
  {'name': "Inflict Wounds", 'level': 1, 'school': 'NEC'},
  {'name': "Insect Plague", 'level': 5, 'school': 'CON'},
  {'name': "Intellect Fortress", 'level': 3, 'school': 'ABJ'},
  {'name': "Investiture of Flame", 'level': 6, 'school': 'TRA'},
  {'name': "Investiture of Ice", 'level': 6, 'school': 'TRA'},
  {'name': "Investiture of Stone", 'level': 6, 'school': 'TRA'},
  {'name': "Investiture of Wind", 'level': 6, 'school': 'TRA'},
  {'name': "Invisibility", 'level': 2, 'school': 'ILL'},
  {'name': "Invulnerability", 'level': 9, 'school': 'ABJ'},
  {'name': "Jallarzi's Storm of Radiance", 'level': 5, 'school': 'EVO'},
  {'name': "Jump", 'level': 1, 'school': 'TRA'},
  {'name': "Kinetic Jaunt", 'level': 2, 'school': 'TRA'},
  {'name': "Knock", 'level': 2, 'school': 'TRA'},
  {'name': "Legend Lore", 'level': 5, 'school': 'DIV'},
  {'name': "Leomund's Secret Chest", 'level': 4, 'school': 'CON'},
  {'name': "Leomund's Tiny Hut", 'level': 3, 'school': 'EVO'},
  {'name': "Lesser Restoration", 'level': 2, 'school': 'ABJ'},
  {'name': "Levitate", 'level': 2, 'school': 'TRA'},
  {'name': "Life Transference", 'level': 3, 'school': 'NEC'},
  {'name': "Light", 'level': 0, 'school': 'EVO'},
  {'name': "Lightning Arrow", 'level': 3, 'school': 'TRA'},
  {'name': "Lightning Bolt", 'level': 3, 'school': 'EVO'},
  {'name': "Lightning Lure", 'level': 0, 'school': 'EVO'},
  {'name': "Lightning Storm", 'level': 7, 'school': 'EVO'},
  {'name': "Lithospheric Blades", 'level': 1, 'school': 'TRA'},
  {'name': "Locate Animals or Plants", 'level': 2, 'school': 'DIV'},
  {'name': "Locate Creature", 'level': 4, 'school': 'DIV'},
  {'name': "Locate Object", 'level': 2, 'school': 'DIV'},
  {'name': "Longstrider", 'level': 1, 'school': 'TRA'},
  {'name': "Maddening Darkness", 'level': 8, 'school': 'EVO'},
  {'name': "Maelstrom", 'level': 5, 'school': 'EVO'},
  {'name': "Mage Armor", 'level': 1, 'school': 'ABJ'},
  {'name': "Mage Hand", 'level': 0, 'school': 'CON'},
  {'name': "Magic Circle", 'level': 3, 'school': 'ABJ'},
  {'name': "Magic Jar", 'level': 6, 'school': 'NEC'},
  {'name': "Magic Missile", 'level': 1, 'school': 'EVO'},
  {'name': "Magic Mouth", 'level': 2, 'school': 'ILL'},
  {'name': "Magic Stone", 'level': 0, 'school': 'TRA'},
  {'name': "Magic Weapon", 'level': 2, 'school': 'TRA'},
  {'name': "Magnify Gravity", 'level': 1, 'school': 'TRA'},
  {'name': "Major Image", 'level': 3, 'school': 'ILL'},
  {'name': "Mass Cure Wounds", 'level': 5, 'school': 'ABJ'},
  {'name': "Mass Heal", 'level': 9, 'school': 'ABJ'},
  {'name': "Mass Healing Word", 'level': 3, 'school': 'ABJ'},
  {'name': "Mass Polymorph", 'level': 9, 'school': 'TRA'},
  {'name': "Mass Suggestion", 'level': 6, 'school': 'ENC'},
  {'name': "Maximilian's Earthen Grasp", 'level': 2, 'school': 'TRA'},
  {'name': "Maze", 'level': 8, 'school': 'CON'},
  {'name': "Meld into Stone", 'level': 3, 'school': 'TRA'},
  {'name': "Melf's Acid Arrow", 'level': 2, 'school': 'EVO'},
  {'name': "Melf's Minute Meteors", 'level': 3, 'school': 'EVO'},
  {'name': "Mending", 'level': 0, 'school': 'TRA'},
  {'name': "Mental Prison", 'level': 6, 'school': 'ILL'},
  {'name': "Message", 'level': 0, 'school': 'TRA'},
  {'name': "Meteor Swarm", 'level': 9, 'school': 'EVO'},
  {'name': "Mighty Fortress", 'level': 8, 'school': 'CON'},
  {'name': "Mind Blank", 'level': 8, 'school': 'ABJ'},
  {'name': "Mind Sliver", 'level': 0, 'school': 'ENC'},
  {'name': "Mind Spike", 'level': 2, 'school': 'DIV'},
  {'name': "Minor Illusion", 'level': 0, 'school': 'ILL'},
  {'name': "Mirage Arcane", 'level': 7, 'school': 'ILL'},
  {'name': "Mirror Image", 'level': 2, 'school': 'ILL'},
  {'name': "Mislead", 'level': 5, 'school': 'ILL'},
  {'name': "Misty Step", 'level': 2, 'school': 'CON'},
  {'name': "Modify Memory", 'level': 5, 'school': 'ENC'},
  {'name': "Mold Earth", 'level': 0, 'school': 'TRA'},
  {'name': "Moonbeam", 'level': 2, 'school': 'EVO'},
  {'name': "Mordenkainen's Faithful Hound", 'level': 4, 'school': 'CON'},
  {'name': "Mordenkainen's Magnificent Mansion", 'level': 7, 'school': 'CON'},
  {'name': "Mordenkainen's Private Sanctum", 'level': 4, 'school': 'ABJ'},
  {'name': "Mordenkainen's Sword", 'level': 7, 'school': 'EVO'},
  {'name': "Move Earth", 'level': 6, 'school': 'TRA'},
  {'name': "Nathair's Mischief", 'level': 2, 'school': 'ILL'},
  {'name': "Negative Energy Flood", 'level': 5, 'school': 'NEC'},
  {'name': "Nondetection", 'level': 3, 'school': 'ABJ'},
  {'name': "Nystul's Magic Aura", 'level': 2, 'school': 'ILL'},
  {'name': "Open Communication", 'level': 4, 'school': 'EVO'},
  {'name': "Otiluke's Freezing Sphere", 'level': 6, 'school': 'EVO'},
  {'name': "Otiluke's Resilient Sphere", 'level': 4, 'school': 'EVO'},
  {'name': "Otto's Irresistible Dance", 'level': 6, 'school': 'ENC'},
  {'name': "Pass without Trace", 'level': 2, 'school': 'ABJ'},
  {'name': "Passwall", 'level': 5, 'school': 'TRA'},
  {'name': "Phantasmal Force", 'level': 2, 'school': 'ILL'},
  {'name': "Phantasmal Killer", 'level': 4, 'school': 'ILL'},
  {'name': "Phantom Steed", 'level': 3, 'school': 'ILL'},
  {'name': "Planar Ally", 'level': 6, 'school': 'CON'},
  {'name': "Planar Binding", 'level': 5, 'school': 'ABJ'},
  {'name': "Plane Shift", 'level': 7, 'school': 'CON'},
  {'name': "Plant Growth", 'level': 3, 'school': 'TRA'},
  {'name': "Poison Spray", 'level': 0, 'school': 'CON'},
  {'name': "Polymorph", 'level': 4, 'school': 'TRA'},
  {'name': "Power Word Fortify", 'level': 7, 'school': 'ENC'},
  {'name': "Power Word Heal", 'level': 9, 'school': 'EVO'},
  {'name': "Power Word Kill", 'level': 9, 'school': 'ENC'},
  {'name': "Power Word Pain", 'level': 7, 'school': 'ENC'},
  {'name': "Power Word Stun", 'level': 8, 'school': 'ENC'},
  {'name': "Prayer of Healing", 'level': 2, 'school': 'EVO'},
  {'name': "Prestidigitation", 'level': 0, 'school': 'TRA'},
  {'name': "Primal Savagery", 'level': 0, 'school': 'TRA'},
  {'name': "Primordial Ward", 'level': 6, 'school': 'ABJ'},
  {'name': "Prismatic Spray", 'level': 7, 'school': 'EVO'},
  {'name': "Prismatic Wall", 'level': 9, 'school': 'ABJ'},
  {'name': "Produce Flame", 'level': 0, 'school': 'CON'},
  {'name': "Programmed Illusion", 'level': 6, 'school': 'ILL'},
  {'name': "Project Image", 'level': 7, 'school': 'ILL'},
  {'name': "Protection from Energy", 'level': 3, 'school': 'ABJ'},
  {'name': "Protection from Evil and Good", 'level': 1, 'school': 'ABJ'},
  {'name': "Protection from Poison", 'level': 2, 'school': 'ABJ'},
  {'name': "Psychic Scream", 'level': 9, 'school': 'ENC'},
  {'name': "Pulse Wave", 'level': 3, 'school': 'EVO'},
  {'name': "Purify Food and Drink", 'level': 1, 'school': 'TRA'},
  {'name': "Pyrotechnics", 'level': 2, 'school': 'TRA'},
  {'name': "Raise Dead", 'level': 5, 'school': 'NEC'},
  {'name': "Rary's Telepathic Bond", 'level': 5, 'school': 'DIV'},
  {'name': "Raulothim's Psychic Lance", 'level': 4, 'school': 'ENC'},
  {'name': "Ravenous Void", 'level': 9, 'school': 'EVO'},
  {'name': "Ray of Enfeeblement", 'level': 2, 'school': 'NEC'},
  {'name': "Ray of Frost", 'level': 0, 'school': 'EVO'},
  {'name': "Ray of Sickness", 'level': 1, 'school': 'NEC'},
  {'name': "Reality Break", 'level': 8, 'school': 'CON'},
  {'name': "Reanimate Greater Monster", 'level': 8, 'school': 'NEC'},
  {'name': "Reanimate Lesser Monster", 'level': 6, 'school': 'NEC'},
  {'name': "Regenerate", 'level': 7, 'school': 'TRA'},
  {'name': "Reincarnate", 'level': 5, 'school': 'TRA'},
  {'name': "Remove curse", 'level': 3, 'school': 'ABJ'},
  {'name': "Resistance", 'level': 0, 'school': 'ABJ'},
  {'name': "Resurrection", 'level': 7, 'school': 'NEC'},
  {'name': "Reverse Gravity", 'level': 7, 'school': 'TRA'},
  {'name': "Revivify", 'level': 3, 'school': 'NEC'},
  {'name': "Rime's Binding Ice", 'level': 2, 'school': 'EVO'},
  {'name': "Rope Trick", 'level': 2, 'school': 'TRA'},
  {'name': "Sacred Flame", 'level': 0, 'school': 'EVO'},
  {'name': "Sanctuary", 'level': 1, 'school': 'ABJ'},
  {'name': "Sapping Sting", 'level': 0, 'school': 'NEC'},
  {'name': "Scatter", 'level': 6, 'school': 'CON'},
  {'name': "Scorching Ray", 'level': 2, 'school': 'EVO'},
  {'name': "Scrying", 'level': 5, 'school': 'DIV'},
  {'name': "Searing Smite", 'level': 1, 'school': 'EVO'},
  {'name': "See Invisibility", 'level': 2, 'school': 'DIV'},
  {'name': "Seeming", 'level': 5, 'school': 'ILL'},
  {'name': "Sending", 'level': 3, 'school': 'DIV'},
  {'name': "Sequester", 'level': 7, 'school': 'TRA'},
  {'name': "Shadow Blade", 'level': 2, 'school': 'ILL'},
  {'name': "Shadow of Moil", 'level': 4, 'school': 'NEC'},
  {'name': "Shape Water", 'level': 0, 'school': 'TRA'},
  {'name': "Shapechange", 'level': 9, 'school': 'TRA'},
  {'name': "Shatter", 'level': 2, 'school': 'EVO'},
  {'name': "Shield", 'level': 1, 'school': 'ABJ'},
  {'name': "Shield of Faith", 'level': 1, 'school': 'ABJ'},
  {'name': "Shillelagh", 'level': 0, 'school': 'TRA'},
  {'name': "Shining Smite", 'level': 2, 'school': 'TRA'},
  {'name': "Shocking Grasp", 'level': 0, 'school': 'EVO'},
  {'name': "Sickening Radiance", 'level': 4, 'school': 'EVO'},
  {'name': "Silence", 'level': 2, 'school': 'ILL'},
  {'name': "Silent Image", 'level': 1, 'school': 'ILL'},
  {'name': "Silvery Barbs", 'level': 1, 'school': 'ENC'},
  {'name': "Simulacrum", 'level': 7, 'school': 'ILL'},
  {'name': "Skill Empowerment", 'level': 5, 'school': 'TRA'},
  {'name': "Skywrite", 'level': 2, 'school': 'TRA'},
  {'name': "Sleep", 'level': 1, 'school': 'ENC'},
  {'name': "Sleet Storm", 'level': 3, 'school': 'CON'},
  {'name': "Slow", 'level': 3, 'school': 'TRA'},
  {'name': "Snare", 'level': 1, 'school': 'ABJ'},
  {'name': "Snilloc's Snowball Swarm", 'level': 2, 'school': 'EVO'},
  {'name': "Soul Cage", 'level': 6, 'school': 'NEC'},
  {'name': "Spare the Dying", 'level': 0, 'school': 'NEC'},
  {'name': "Speak with Animals", 'level': 1, 'school': 'DIV'},
  {'name': "Speak with Dead", 'level': 3, 'school': 'NEC'},
  {'name': "Speak with Plants", 'level': 3, 'school': 'TRA'},
  {'name': "Spider Climb", 'level': 2, 'school': 'TRA'},
  {'name': "Spike Growth", 'level': 2, 'school': 'TRA'},
  {'name': "Spirit Guardians", 'level': 3, 'school': 'CON'},
  {'name': "Spirit of Death", 'level': 4, 'school': 'NEC'},
  {'name': "Spirit Shroud", 'level': 3, 'school': 'NEC'},
  {'name': "Spiritual Weapon", 'level': 2, 'school': 'EVO'},
  {'name': "Spray of Cards", 'level': 2, 'school': 'CON'},
  {'name': "Staggering Smite", 'level': 4, 'school': 'EVO'},
  {'name': "Starry Wisp", 'level': 0, 'school': 'EVO'},
  {'name': "Steel Wind Strike", 'level': 5, 'school': 'CON'},
  {'name': "Stinking Cloud", 'level': 3, 'school': 'CON'},
  {'name': "Stone Shape", 'level': 4, 'school': 'TRA'},
  {'name': "Stoneskin", 'level': 4, 'school': 'ABJ'},
  {'name': "Storm of Vengeance", 'level': 9, 'school': 'CON'},
  {'name': "Storm Sphere", 'level': 4, 'school': 'EVO'},
  {'name': "Suggestion", 'level': 2, 'school': 'ENC'},
  {'name': "Summon Aberration", 'level': 4, 'school': 'CON'},
  {'name': "Summon Beast", 'level': 2, 'school': 'CON'},
  {'name': "Summon Celestial", 'level': 5, 'school': 'CON'},
  {'name': "Summon Construct", 'level': 4, 'school': 'CON'},
  {'name': "Summon Dragon", 'level': 5, 'school': 'CON'},
  {'name': "Summon Elemental", 'level': 4, 'school': 'CON'},
  {'name': "Summon Fey", 'level': 3, 'school': 'CON'},
  {'name': "Summon Fiend", 'level': 6, 'school': 'CON'},
  {'name': "Summon Greater Demon", 'level': 4, 'school': 'CON'},
  {'name': "Summon Lesser Demon", 'level': 3, 'school': 'CON'},
  {'name': "Summon Shadowspawn", 'level': 3, 'school': 'CON'},
  {'name': "Summon Undead", 'level': 3, 'school': 'NEC'},
  {'name': "Sunbeam", 'level': 6, 'school': 'EVO'},
  {'name': "Sunburst", 'level': 8, 'school': 'EVO'},
  {'name': "Swift Quiver", 'level': 5, 'school': 'TRA'},
  {'name': "Sword Burst", 'level': 0, 'school': 'CON'},
  {'name': "Symbol", 'level': 7, 'school': 'ABJ'},
  {'name': "Synaptic Static", 'level': 5, 'school': 'ENC'},
  {'name': "Tasha's Bubbling Cauldron", 'level': 6, 'school': 'CON'},
  {'name': "Tasha's Caustic Brew", 'level': 1, 'school': 'EVO'},
  {'name': "Tasha's Hideous Laughter", 'level': 1, 'school': 'ENC'},
  {'name': "Tasha's Mind Whip", 'level': 2, 'school': 'ENC'},
  {'name': "Tasha's Otherworldly Guise", 'level': 6, 'school': 'TRA'},
  {'name': "Telekinesis", 'level': 5, 'school': 'TRA'},
  {'name': "Telepathy", 'level': 8, 'school': 'DIV'},
  {'name': "Teleport", 'level': 7, 'school': 'CON'},
  {'name': "Teleportation Circle", 'level': 5, 'school': 'CON'},
  {'name': "Temple of the Gods", 'level': 7, 'school': 'CON'},
  {'name': "Temporal Shunt", 'level': 5, 'school': 'TRA'},
  {'name': "Tenser's Floating Disk", 'level': 1, 'school': 'CON'},
  {'name': "Tenser's Transformation", 'level': 6, 'school': 'TRA'},
  {'name': "Tether Essence", 'level': 7, 'school': 'NEC'},
  {'name': "Thaumaturgy", 'level': 0, 'school': 'TRA'},
  {'name': "Thorn Whip", 'level': 0, 'school': 'TRA'},
  {'name': "Thunder Step", 'level': 3, 'school': 'CON'},
  {'name': "Thunderclap", 'level': 0, 'school': 'EVO'},
  {'name': "Thunderous Smite", 'level': 1, 'school': 'EVO'},
  {'name': "Thunderwave", 'level': 1, 'school': 'EVO'},
  {'name': "Tidal Wave", 'level': 3, 'school': 'CON'},
  {'name': "Time Ravage", 'level': 9, 'school': 'NEC'},
  {'name': "Time Stop", 'level': 9, 'school': 'TRA'},
  {'name': "Tiny Servant", 'level': 3, 'school': 'TRA'},
  {'name': "Toll the Dead", 'level': 0, 'school': 'NEC'},
  {'name': "Tongues", 'level': 3, 'school': 'DIV'},
  {'name': "Transmute Rock", 'level': 5, 'school': 'TRA'},
  {'name': "Transport via Plants", 'level': 6, 'school': 'CON'},
  {'name': "Tree Stride", 'level': 5, 'school': 'CON'},
  {'name': "True Polymorph", 'level': 9, 'school': 'TRA'},
  {'name': "True Resurrection", 'level': 9, 'school': 'NEC'},
  {'name': "True Seeing", 'level': 6, 'school': 'DIV'},
  {'name': "True Strike", 'level': 0, 'school': 'DIV'},
  {'name': "Tsunami", 'level': 8, 'school': 'CON'},
  {'name': "Unseen Servant", 'level': 1, 'school': 'CON'},
  {'name': "Vampiric Touch", 'level': 3, 'school': 'NEC'},
  {'name': "Vicious Mockery", 'level': 0, 'school': 'ENC'},
  {'name': "Vitriolic Sphere", 'level': 4, 'school': 'EVO'},
  {'name': "Vortex Warp", 'level': 2, 'school': 'CON'},
  {'name': "Wall of Fire", 'level': 4, 'school': 'EVO'},
  {'name': "Wall of Force", 'level': 5, 'school': 'EVO'},
  {'name': "Wall of Ice", 'level': 6, 'school': 'EVO'},
  {'name': "Wall of Light", 'level': 5, 'school': 'EVO'},
  {'name': "Wall of Sand", 'level': 3, 'school': 'EVO'},
  {'name': "Wall of Stone", 'level': 5, 'school': 'EVO'},
  {'name': "Wall of Thorns", 'level': 6, 'school': 'CON'},
  {'name': "Wall of Water", 'level': 3, 'school': 'EVO'},
  {'name': "Warding Bond", 'level': 2, 'school': 'ABJ'},
  {'name': "Warding Wind", 'level': 2, 'school': 'EVO'},
  {'name': "Water Breathing", 'level': 3, 'school': 'TRA'},
  {'name': "Water Walk", 'level': 3, 'school': 'TRA'},
  {'name': "Watery Sphere", 'level': 4, 'school': 'CON'},
  {'name': "Web", 'level': 2, 'school': 'CON'},
  {'name': "Weird", 'level': 9, 'school': 'ILL'},
  {'name': "Whirlwind", 'level': 7, 'school': 'EVO'},
  {'name': "Wind Walk", 'level': 6, 'school': 'TRA'},
  {'name': "Wind Wall", 'level': 3, 'school': 'EVO'},
  {'name': "Wish", 'level': 9, 'school': 'CON'},
  {'name': "Witch Bolt", 'level': 1, 'school': 'EVO'},
  {'name': "Wither and Bloom", 'level': 2, 'school': 'NEC'},
  {'name': "Word of Radiance", 'level': 0, 'school': 'EVO'},
  {'name': "Word of Recall", 'level': 6, 'school': 'CON'},
  {'name': "Wrath of Nature", 'level': 5, 'school': 'EVO'},
  {'name': "Wrathful Smite", 'level': 1, 'school': 'EVO'},
  {'name': "Wristpocket", 'level': 2, 'school': 'CON'},
  {'name': "Yolande's Regal Presence", 'level': 5, 'school': 'TRA'},
  {'name': "Zephyr Strike", 'level': 1, 'school': 'TRA'},
  {'name': "Zone of Truth", 'level': 2, 'school': 'ENC'},
]
