WEAPONS = [
  {
    'name': 'Club',
    'price': '1',
    'damage_type': 'BLG',
    'weapon_class': 'BLN',
    'martial': 'False',
    'ranged': 'False',
    'mastery': 'SLW',
    'ammunition': False,
    'finesse': False,
    'heavy': False,
    'light': True,
    'loading': False,
    'reach': False,
    'thrown': False,
    'two_handed': False,
    'versatile': False,
  },
  {
    'name': 'Dagger',
    'price': '2',
    'damage_type': 'PRC',
    'weapon_class': 'DGR',
    'martial': 'False',
    'ranged': 'False',
    'mastery': 'NIC',
    'ammunition': False,
    'finesse': True,
    'heavy': False,
    'light': True,
    'loading': False,
    'reach': False,
    'thrown': True,
    'two_handed': False,
    'versatile': False,
  },
  {
    'name': 'Greatclub',
    'price': '1',
    'damage_type': 'BLG',
    'weapon_class': 'BLN',
    'martial': 'False',
    'ranged': 'False',
    'mastery': 'PSH',
    'ammunition': False,
    'finesse': False,
    'heavy': False,
    'light': False,
    'loading': False,
    'reach': False,
    'thrown': False,
    'two_handed': True,
    'versatile': False,
  },
  {
    'name': 'Handaxe',
    'price': '5',
    'damage_type': 'SLA',
    'weapon_class': 'AXE',
    'martial': 'False',
    'ranged': 'False',
    'mastery': 'VEX',
    'ammunition': False,
    'finesse': False,
    'heavy': False,
    'light': True,
    'loading': False,
    'reach': False,
    'thrown': True,
    'two_handed': False,
    'versatile': False,
  },
  {
    'name': 'Javelin',
    'price': '1',
    'damage_type': 'PRC',
    'weapon_class': 'SPR',
    'martial': 'False',
    'ranged': 'False',
    'mastery': 'SLW',
    'ammunition': False,
    'finesse': False,
    'heavy': False,
    'light': False,
    'loading': False,
    'reach': False,
    'thrown': True,
    'two_handed': False,
    'versatile': False,
  },
  {
    'name': 'Light Hammer',
    'price': '2',
    'damage_type': 'BLG',
    'weapon_class': 'BLN',
    'martial': 'False',
    'ranged': 'False',
    'mastery': 'NIC',
    'ammunition': False,
    'finesse': False,
    'heavy': False,
    'light': True,
    'loading': False,
    'reach': False,
    'thrown': True,
    'two_handed': False,
    'versatile': False,
  },
  {
    'name': 'Mace',
    'price': '5',
    'damage_type': 'BLG',
    'weapon_class': 'BLN',
    'martial': 'False',
    'ranged': 'False',
    'mastery': 'SAP',
    'ammunition': False,
    'finesse': False,
    'heavy': False,
    'light': False,
    'loading': False,
    'reach': False,
    'thrown': False,
    'two_handed': False,
    'versatile': False,
  },
  {
    'name': 'Quarterstaff',
    'price': '1',
    'damage_type': 'BLG',
    'weapon_class': 'BLN',
    'martial': 'False',
    'ranged': 'False',
    'mastery': 'TPL',
    'ammunition': False,
    'finesse': False,
    'heavy': False,
    'light': False,
    'loading': False,
    'reach': False,
    'thrown': False,
    'two_handed': False,
    'versatile': True,
  },
  {
    'name': 'Sickle',
    'price': '1',
    'damage_type': 'SLA',
    'weapon_class': 'SKL',
    'martial': 'False',
    'ranged': 'False',
    'mastery': 'NIC',
    'ammunition': False,
    'finesse': False,
    'heavy': False,
    'light': True,
    'loading': False,
    'reach': False,
    'thrown': False,
    'two_handed': False,
    'versatile': False,
  },
  {
    'name': 'Spear',
    'price': '1',
    'damage_type': 'PRC',
    'weapon_class': 'SPR',
    'martial': 'False',
    'ranged': 'False',
    'mastery': 'SAP',
    'ammunition': False,
    'finesse': False,
    'heavy': False,
    'light': False,
    'loading': False,
    'reach': False,
    'thrown': True,
    'two_handed': False,
    'versatile': True,
  },
  {
    'name': 'Light Crossbow',
    'price': '25',
    'damage_type': 'PRC',
    'weapon_class': 'CSB',
    'martial': 'False',
    'ranged': 'True',
    'mastery': 'SLW',
    'ammunition': True,
    'finesse': False,
    'heavy': False,
    'light': False,
    'loading': True,
    'reach': False,
    'thrown': False,
    'two_handed': True,
    'versatile': False,
  },
  {
    'name': 'Dart',
    'price': '1',
    'damage_type': 'PRC',
    'weapon_class': 'DRT',
    'martial': 'False',
    'ranged': 'True',
    'mastery': 'VEX',
    'ammunition': False,
    'finesse': True,
    'heavy': False,
    'light': False,
    'loading': False,
    'reach': False,
    'thrown': True,
    'two_handed': False,
    'versatile': False,
  },
  {
    'name': 'Shortbow',
    'price': '25',
    'damage_type': 'PRC',
    'weapon_class': 'BOW',
    'martial': 'False',
    'ranged': 'True',
    'mastery': 'VEX',
    'ammunition': True,
    'finesse': False,
    'heavy': False,
    'light': False,
    'loading': False,
    'reach': False,
    'thrown': False,
    'two_handed': True,
    'versatile': False,
  },
  {
    'name': 'Sling',
    'price': '1',
    'damage_type': 'BLG',
    'weapon_class': 'SLN',
    'martial': 'False',
    'ranged': 'True',
    'mastery': 'SLW',
    'ammunition': True,
    'finesse': False,
    'heavy': False,
    'light': False,
    'loading': False,
    'reach': False,
    'thrown': False,
    'two_handed': False,
    'versatile': False,
  },
  {
    'name': 'Battleaxe',
    'price': '10',
    'damage_type': 'SLA',
    'weapon_class': 'AXE',
    'martial': 'True',
    'ranged': 'False',
    'mastery': 'TPL',
    'ammunition': False,
    'finesse': False,
    'heavy': False,
    'light': False,
    'loading': False,
    'reach': False,
    'thrown': False,
    'two_handed': False,
    'versatile': True,
  },
  {
    'name': 'Flail',
    'price': '10',
    'damage_type': 'BLG',
    'weapon_class': 'BLN',
    'martial': 'True',
    'ranged': 'False',
    'mastery': 'SAP',
    'ammunition': False,
    'finesse': False,
    'heavy': False,
    'light': False,
    'loading': False,
    'reach': False,
    'thrown': False,
    'two_handed': False,
    'versatile': False,
  },
  {
    'name': 'Glaive',
    'price': '20',
    'damage_type': 'SLA',
    'weapon_class': 'PLM',
    'martial': 'True',
    'ranged': 'False',
    'mastery': 'GRZ',
    'ammunition': False,
    'finesse': False,
    'heavy': True,
    'light': False,
    'loading': False,
    'reach': True,
    'thrown': False,
    'two_handed': True,
    'versatile': False,
  },
  {
    'name': 'Greataxe',
    'price': '30',
    'damage_type': 'SLA',
    'weapon_class': 'AXE',
    'martial': 'True',
    'ranged': 'False',
    'mastery': 'CLV',
    'ammunition': False,
    'finesse': False,
    'heavy': True,
    'light': False,
    'loading': False,
    'reach': False,
    'thrown': False,
    'two_handed': True,
    'versatile': False,
  },
  {
    'name': 'Greatsword',
    'price': '50',
    'damage_type': 'SLA',
    'weapon_class': 'SWD',
    'martial': 'True',
    'ranged': 'False',
    'mastery': 'GRZ',
    'ammunition': False,
    'finesse': False,
    'heavy': True,
    'light': False,
    'loading': False,
    'reach': False,
    'thrown': False,
    'two_handed': True,
    'versatile': False,
  },
  {
    'name': 'Halberd',
    'price': '20',
    'damage_type': 'SLA',
    'weapon_class': 'PLM',
    'martial': 'True',
    'ranged': 'False',
    'mastery': 'CLV',
    'ammunition': False,
    'finesse': False,
    'heavy': True,
    'light': False,
    'loading': False,
    'reach': True,
    'thrown': False,
    'two_handed': True,
    'versatile': False,
  },
  {
    'name': 'Lance',
    'price': '10',
    'damage_type': 'PRC',
    'weapon_class': 'LAN',
    'martial': 'True',
    'ranged': 'False',
    'mastery': 'TPL',
    'ammunition': False,
    'finesse': False,
    'heavy': True,
    'light': False,
    'loading': False,
    'reach': True,
    'thrown': False,
    'two_handed': True,
    'versatile': False,
  },
  {
    'name': 'Longsword',
    'price': '15',
    'damage_type': 'SLA',
    'weapon_class': 'SWD',
    'martial': 'True',
    'ranged': 'False',
    'mastery': 'SAP',
    'ammunition': False,
    'finesse': False,
    'heavy': False,
    'light': False,
    'loading': False,
    'reach': False,
    'thrown': False,
    'two_handed': False,
    'versatile': True,
  },
  {
    'name': 'Maul',
    'price': '10',
    'damage_type': 'BLG',
    'weapon_class': 'BLN',
    'martial': 'True',
    'ranged': 'False',
    'mastery': 'TPL',
    'ammunition': False,
    'finesse': False,
    'heavy': True,
    'light': False,
    'loading': False,
    'reach': False,
    'thrown': False,
    'two_handed': True,
    'versatile': False,
  },
  {
    'name': 'Morningstar',
    'price': '15',
    'damage_type': 'PRC',
    'weapon_class': 'BLN',
    'martial': 'True',
    'ranged': 'False',
    'mastery': 'SAP',
    'ammunition': False,
    'finesse': False,
    'heavy': False,
    'light': False,
    'loading': False,
    'reach': False,
    'thrown': False,
    'two_handed': False,
    'versatile': False,
  },
  {
    'name': 'Pike',
    'price': '5',
    'damage_type': 'PRC',
    'weapon_class': 'PLM',
    'martial': 'True',
    'ranged': 'False',
    'mastery': 'PSH',
    'ammunition': False,
    'finesse': False,
    'heavy': True,
    'light': False,
    'loading': False,
    'reach': True,
    'thrown': False,
    'two_handed': True,
    'versatile': False,
  },
  {
    'name': 'Rapier',
    'price': '25',
    'damage_type': 'PRC',
    'weapon_class': 'SWD',
    'martial': 'True',
    'ranged': 'False',
    'mastery': 'VEX',
    'ammunition': False,
    'finesse': True,
    'heavy': False,
    'light': False,
    'loading': False,
    'reach': False,
    'thrown': False,
    'two_handed': False,
    'versatile': False,
  },
  {
    'name': 'Scimitar',
    'price': '25',
    'damage_type': 'SLA',
    'weapon_class': 'SWD',
    'martial': 'True',
    'ranged': 'False',
    'mastery': 'NIC',
    'ammunition': False,
    'finesse': True,
    'heavy': False,
    'light': True,
    'loading': False,
    'reach': False,
    'thrown': False,
    'two_handed': False,
    'versatile': False,
  },
  {
    'name': 'Shortsword',
    'price': '10',
    'damage_type': 'PRC',
    'weapon_class': 'SWD',
    'martial': 'True',
    'ranged': 'False',
    'mastery': 'VEX',
    'ammunition': False,
    'finesse': True,
    'heavy': False,
    'light': True,
    'loading': False,
    'reach': False,
    'thrown': False,
    'two_handed': False,
    'versatile': False,
  },
  {
    'name': 'Trident',
    'price': '5',
    'damage_type': 'PRC',
    'weapon_class': 'SPR',
    'martial': 'True',
    'ranged': 'False',
    'mastery': 'TPL',
    'ammunition': False,
    'finesse': False,
    'heavy': False,
    'light': False,
    'loading': False,
    'reach': False,
    'thrown': True,
    'two_handed': False,
    'versatile': True,
  },
  {
    'name': 'War Pick',
    'price': '5',
    'damage_type': 'PRC',
    'weapon_class': 'PIC',
    'martial': 'True',
    'ranged': 'False',
    'mastery': 'SAP',
    'ammunition': False,
    'finesse': False,
    'heavy': False,
    'light': False,
    'loading': False,
    'reach': False,
    'thrown': False,
    'two_handed': False,
    'versatile': True,
  },
  {
    'name': 'Warhammer',
    'price': '15',
    'damage_type': 'BLG',
    'weapon_class': 'BLN',
    'martial': 'True',
    'ranged': 'False',
    'mastery': 'PSH',
    'ammunition': False,
    'finesse': False,
    'heavy': False,
    'light': False,
    'loading': False,
    'reach': False,
    'thrown': False,
    'two_handed': False,
    'versatile': True,
  },
  {
    'name': 'Whip',
    'price': '2',
    'damage_type': 'SLA',
    'weapon_class': 'WHP',
    'martial': 'True',
    'ranged': 'False',
    'mastery': 'SLW',
    'ammunition': False,
    'finesse': True,
    'heavy': False,
    'light': False,
    'loading': False,
    'reach': True,
    'thrown': False,
    'two_handed': False,
    'versatile': False,
  },
  {
    'name': 'Blowgun',
    'price': '10',
    'damage_type': 'PRC',
    'weapon_class': 'BLG',
    'martial': 'True',
    'ranged': 'True',
    'mastery': 'VEX',
    'ammunition': True,
    'finesse': False,
    'heavy': False,
    'light': False,
    'loading': True,
    'reach': False,
    'thrown': False,
    'two_handed': False,
    'versatile': False,
  },
  {
    'name': 'Hand Crossbow',
    'price': '75',
    'damage_type': 'PRC',
    'weapon_class': 'CSB',
    'martial': 'True',
    'ranged': 'True',
    'mastery': 'VEX',
    'ammunition': True,
    'finesse': False,
    'heavy': False,
    'light': True,
    'loading': True,
    'reach': False,
    'thrown': False,
    'two_handed': False,
    'versatile': False,
  },
  {
    'name': 'Heavy Crossbow',
    'price': '50',
    'damage_type': 'PRC',
    'weapon_class': 'CSB',
    'martial': 'True',
    'ranged': 'True',
    'mastery': 'PSH',
    'ammunition': True,
    'finesse': False,
    'heavy': True,
    'light': False,
    'loading': True,
    'reach': False,
    'thrown': False,
    'two_handed': True,
    'versatile': False,
  },
  {
    'name': 'Longbow',
    'price': '50',
    'damage_type': 'PRC',
    'weapon_class': 'BOW',
    'martial': 'True',
    'ranged': 'True',
    'mastery': 'SLW',
    'ammunition': True,
    'finesse': False,
    'heavy': True,
    'light': False,
    'loading': False,
    'reach': False,
    'thrown': False,
    'two_handed': True,
    'versatile': False,
  },
  {
    'name': 'Musket',
    'price': '500',
    'damage_type': 'PRC',
    'weapon_class': 'FRM',
    'martial': 'True',
    'ranged': 'True',
    'mastery': 'SLW',
    'ammunition': True,
    'finesse': False,
    'heavy': False,
    'light': False,
    'loading': True,
    'reach': False,
    'thrown': False,
    'two_handed': True,
    'versatile': False,
  },
  {
    'name': 'Pistol',
    'price': '250',
    'damage_type': 'PRC',
    'weapon_class': 'FRM',
    'martial': 'True',
    'ranged': 'True',
    'mastery': 'VEX',
    'ammunition': True,
    'finesse': False,
    'heavy': False,
    'light': False,
    'loading': True,
    'reach': False,
    'thrown': False,
    'two_handed': False,
    'versatile': False,
  },
]