# Generated by Django 5.2 on 2025-04-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('LIT', 'Light'), ('MED', 'Medium'), ('HEV', 'Heavy')], default='LIT', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('price', models.IntegerField()),
                ('attunement', models.BooleanField(default=False)),
                ('rarity', models.CharField(choices=[('C', 'Common'), ('U', 'Uncommon'), ('R', 'Rare'), ('V', 'Very Rare'), ('L', 'Legendary'), ('A', 'Artifact')], default='C', max_length=1)),
                ('category', models.CharField(choices=[('WON', 'Wondrous Item'), ('ARM', 'Armor'), ('CLS', 'Class Item'), ('CLO', 'Clothing'), ('CON', 'Consumable'), ('JWL', 'Jewelry'), ('SCR', 'Spell Scroll'), ('TAT', 'Tattoo'), ('WND', 'Wand/Staff'), ('WPN', 'Weapon')], default='WON', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('level', models.IntegerField(choices=[(0, 'Cantrip'), (1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4st'), (5, '5st'), (6, '6st'), (7, '7st'), (8, '8st'), (9, '9st')], default=0)),
                ('school', models.CharField(choices=[('ABJ', 'Abjuration'), ('CON', 'Conjuration'), ('DIV', 'Divination'), ('ENC', 'Enchantment'), ('EVO', 'Evocation'), ('ILL', 'Illusion'), ('NEC', 'Necromancy'), ('TRA', 'Transmutation')], default='EVO', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('damage_type', models.CharField(choices=[('BLG', 'Bludgeoning'), ('PRC', 'Piercing'), ('SLA', 'Slashing')], default='BLG', max_length=3)),
                ('weapon_class', models.CharField(choices=[('AXE', 'Axe'), ('BLG', 'Blowgun'), ('BLN', 'Blunt'), ('BMG', 'Boomerang'), ('BOW', 'Bow'), ('CSB', 'Crossbow'), ('DGR', 'Dagger'), ('DRT', 'Dart'), ('FRM', 'Firearm'), ('LAN', 'Lance'), ('PIC', 'Pick'), ('PLM', 'Polearm'), ('SKL', 'Sickle'), ('SLN', 'Sling'), ('SPR', 'Spear'), ('SWD', 'Sword'), ('WHP', 'Whip')], default='BLG', max_length=3)),
                ('martial', models.BooleanField(default=False)),
                ('ranged', models.BooleanField(default=False)),
                ('mastery', models.CharField(choices=[('CLV', 'Cleave'), ('GRZ', 'Graze'), ('NIC', 'Nick'), ('PSH', 'Push'), ('SAP', 'Sap'), ('SLW', 'Slow'), ('TPL', 'Topple'), ('VEX', 'Vex')], default='CLV', max_length=3)),
                ('ammunition', models.BooleanField(default=False)),
                ('finesse', models.BooleanField(default=False)),
                ('heavy', models.BooleanField(default=False)),
                ('light', models.BooleanField(default=False)),
                ('loading', models.BooleanField(default=False)),
                ('reach', models.BooleanField(default=False)),
                ('thrown', models.BooleanField(default=False)),
                ('two_handed', models.BooleanField(default=False)),
                ('versatile', models.BooleanField(default=False)),
            ],
        ),
    ]
