# Generated by Django 5.2 on 2025-08-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legendlore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('WON', 'Wondrous Item'), ('ARM', 'Armor'), ('AMM', 'Ammunition'), ('CLS', 'Class Item'), ('CLO', 'Clothing'), ('CON', 'Consumable'), ('JWL', 'Jewelry'), ('SCR', 'Spell Scroll'), ('TAT', 'Tattoo'), ('WND', 'Wand/Staff'), ('WPN', 'Weapon')], default='WON', max_length=3),
        ),
        migrations.AlterField(
            model_name='spell',
            name='level',
            field=models.IntegerField(choices=[(0, 'Cantrip'), (1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th')], default=0),
        ),
    ]
