# Generated by Django 5.2 on 2025-08-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legendlore', '0002_alter_item_category_alter_spell_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='armor_options',
            field=models.ManyToManyField(related_name='items', related_query_name='item', to='legendlore.armor'),
        ),
        migrations.AddField(
            model_name='item',
            name='spell_options',
            field=models.ManyToManyField(related_name='items', related_query_name='item', to='legendlore.spell'),
        ),
        migrations.AddField(
            model_name='item',
            name='weapon_options',
            field=models.ManyToManyField(related_name='items', related_query_name='item', to='legendlore.weapon'),
        ),
        migrations.AlterField(
            model_name='armor',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=240, unique=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
