# Generated by Django 5.2 on 2025-08-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legendlore', '0003_item_armor_options_item_spell_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='armor_options',
            field=models.ManyToManyField(blank=True, related_name='items', related_query_name='item', to='legendlore.armor'),
        ),
        migrations.AlterField(
            model_name='item',
            name='spell_options',
            field=models.ManyToManyField(blank=True, related_name='items', related_query_name='item', to='legendlore.spell'),
        ),
        migrations.AlterField(
            model_name='item',
            name='weapon_options',
            field=models.ManyToManyField(blank=True, related_name='items', related_query_name='item', to='legendlore.weapon'),
        ),
    ]
