# Generated by Django 5.2 on 2025-08-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legendlore', '0004_alter_item_armor_options_alter_item_spell_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='category',
            field=models.CharField(choices=[('LIT', 'Light'), ('MED', 'Medium'), ('HEV', 'Heavy'), ('SHL', 'Shield')], default='LIT', max_length=3),
        ),
    ]
