# Generated by Django 5.2.5 on 2025-08-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legendlore', '0005_alter_armor_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rarity',
            field=models.CharField(choices=[('M', 'Mundane'), ('C', 'Common'), ('U', 'Uncommon'), ('R', 'Rare'), ('V', 'Very Rare'), ('L', 'Legendary'), ('A', 'Artifact')], default='C', max_length=1),
        ),
    ]
